### ISSUE TITLE
Thanks

### ISSUE THREAD

**Issue by Reinbert** [fablab-bayreuth/coinspi#1]
This is exactly the point where I am just now. Got it working nicely but the 5+ second transmission time is just ridiculous. 

I thought about using an ATtiny8 for your code but that doesn't seem to have UART pins. But there's probably software for that.

Cheers, Reini

**Comment by Cat-Ion** [comment]
Well, you can always bitbang the UART. I just had about a dozen atmega8s lying around, so I used one of those.
